const fs=require('fs');
function tr(file, pairs) {
  if (!fs.existsSync(file)) return;
  let html = fs.readFileSync(file, 'utf8');
  let c = 0;
  pairs.forEach(([k, v]) => {
    if (html.includes(k)) { html = html.split(k).join(v); c++; }
  });
  if (c > 0) { fs.writeFileSync(file, html, 'utf8'); console.log(file + ': ' + c); }
}

// ===== login-en.html =====
tr('login-en.html', [
  ['← Home 돌아가기', '← Back to Home'],
  ['>사용자<', '>User<'],
  ['로그아웃', 'Sign Out'],
  ['알림 설정 →', 'Notification Settings →'],
  ["'사용자'", "'User'"],
  ['Supabase가 아직 설정되지 않았습니다.', 'Supabase is not configured yet.'],
  ['Supabase 설정 방법:', 'How to set up Supabase:'],
  ['1. supabase.com에서 프로젝트 생성', '1. Create a project at supabase.com'],
  ['2. Authentication > Providers에서 Google 활성화', '2. Enable Google under Authentication > Providers'],
  ['3. login.html의 SUPABASE_URL, SUPABASE_ANON_KEY 교체', '3. Replace SUPABASE_URL and SUPABASE_ANON_KEY'],
  ['4. Supabase 대시보드에서 Site URL을 본인 도메인으로 설정', '4. Set Site URL to your domain in Supabase dashboard'],
  [' 로그인은 Supabase에서 커스텀 OAuth 설정이 필요합니다.', ' login requires custom OAuth setup in Supabase.'],
  ['우선 Google 로그인을 사용해주세요.', 'Please use Google login for now.'],
  ["'로그인 실패: '", "'Login failed: '"],
  ["'로그인 오류: '", "'Login error: '"],
  ["'이메일 주소를 입력하세요:'", "'Enter your email address:'"],
  ["'Supabase가 아직 설정되지 않았습니다.'", "'Supabase is not configured yet.'"],
  ["'오류: '", "'Error: '"],
  ["'매직 링크가 '", "'A magic link has been sent to '"],
  ["'로 발송되었습니다. 이메일을 확인해주세요!'", "'. Please check your email!'"],
  ['// Supabase 초기화', '// Initialize Supabase'],
  ['// 로그인 상태 체크', '// Check login status'],
]);

// ===== jobs-en.html =====
tr('jobs-en.html', [
  ['지금 열려있는', 'Now Open'],
  ['<em>글로벌 항공사 채용</em>', '<em>Global Airline Careers</em>'],
  ['에미레이트, 카타르, 싱가포르, 캐세이, 대한항공, 아시아나   주요 항공사 채용 소식을 한 곳에서 확인하세요.', 'Emirates, Qatar, Singapore, Cathay, Korean Air, Asiana — all major airline recruitment in one place.'],
  ['항공사별 <em>채용 현황</em>', 'Airline <em>Recruitment Status</em>'],
  ['>채용중<', '>Hiring<'],
  ['>준비중<', '>Upcoming<'],
  ['상시</span>', 'Rolling</span>'],
  ['예정</span>', 'TBA</span>'],
  ['두바이 베이스', 'Dubai base'],
  ['서울 오픈데이 예정', 'Seoul Open Day scheduled'],
  ['영어 면접 + 암리치 테스트 포함', 'Includes English interview + arm-reach test'],
  ['도하 베이스', 'Doha base'],
  ['한국인 승무원 상시 채용 중', 'Rolling recruitment for Korean crew'],
  ['온라인 CV 심사부터 시작', 'Starts with online CV screening'],
  ['싱가포르 베이스', 'Singapore base'],
  ['서울 채용설명회 및 면접', 'Seoul recruitment info session & interview'],
  ['스몰톡 + 그룹 인터뷰', 'Small talk + group interview'],
  ['홍콩 베이스', 'Hong Kong base'],
  ['2026 Cabin Crew 채용', '2026 Cabin Crew recruitment'],
  ['영어 면접 + Safety Demo', 'English interview + Safety Demo'],
  ['국내 최대 FSC', "Korea's largest FSC"],
  ['하반기 신입 객실승무원 공개채용 예정', 'Entry-level cabin crew open recruitment expected H2'],
  ['스타얼라이언스 소속', 'Star Alliance member'],
  ['인천 베이스', 'Incheon base'],
  ['공개채용 일정 공고 대기 중', 'Waiting for open recruitment announcement'],
  ['면접과정', 'Interview Process'],
  ['채용 · 뉴스', 'Recruitment News'],
  ['<em>채용 뉴스</em>', '<em>Recruitment News</em>'],
  ['항공사 채용 뉴스를 실시간으로 업데이트합니다.', 'Real-time airline recruitment news updates.'],
  ['에미레이트항공 서울 오픈데이 개최', 'Emirates Seoul Open Day Announced'],
  ['카타르항공 한국인 승무원 상시채용', 'Qatar Airways Korean Crew Rolling Recruitment'],
  ['대한항공 신입 객실승무원 공개채용 예정', 'Korean Air New Cabin Crew Recruitment'],
  ['싱가포르항공 채용설명회 안내', 'Singapore Airlines Recruitment Info Session'],
  ['캐세이퍼시픽 2026 Cabin Crew 모집', 'Cathay Pacific 2026 Cabin Crew Recruitment'],
  ['아시아나항공 채용 공고 업데이트', 'Asiana Airlines Recruitment Update'],
  ['에티하드항공 아부다비 베이스 채용', 'Etihad Airways Abu Dhabi Recruitment'],
  ['핀에어 헬싱키 채용 오픈', 'Finnair Helsinki Recruitment Open'],
  ['진에어 신입 객실승무원 모집', 'Jin Air New Cabin Crew Recruitment'],
  ['에어프레미아 중장거리 노선 확대 채용', 'Air Premia Long-haul Expansion Recruitment'],
  ['전체 뉴스 보기 →', 'View All News →'],
]);

// ===== community-en.html =====
tr('community-en.html', [
  ['함께 준비하면', 'Prepare Together,'],
  ['<em>합격이 가까워져요</em>', '<em>Get Closer to Success</em>'],
  ['스터디를 구하고, 고민을 나누고, Interview Reviews와 Success Stories를 공유하세요.', 'Find study partners, share concerns, post interview reviews and success stories.'],
  ['스터디 구해요', 'Study Groups'],
  ['내 주변 / 같은 항공사 스터디 찾기', 'Find nearby study groups for same airline'],
  ['자유롭게 이야기해요', 'Free Discussion'],
  ['면접 고민, 항공사 정보, 자유 토론', 'Interview worries, airline info, open discussion'],
  ['어땠나요?', 'How Was It?'],
  ['실제 면접 경험 공유', 'Share real interview experiences'],
  ['합격했어요!', 'I Got Accepted!'],
  ['합격 후기와 꿀팁 공유', 'Share success stories and tips'],
  ['0개', '0'],
  ['에미레이트 스터디원 구합니다', 'Looking for Emirates study partners'],
  ['서울 강남 / 주 2회 / 영어 인터뷰', 'Seoul Gangnam / 2x week / English interview'],
  ['카타르 파이널 준비 스터디', 'Qatar Final Prep Study Group'],
  ['온라인 / 주 3회 / 파이널 집중', 'Online / 3x week / Final focus'],
  ['대한항공 면접 스터디', 'Korean Air Interview Study'],
  ['서울 / 주 2회 / 한국어 면접', 'Seoul / 2x week / Korean interview'],
  ['참여', 'Join'],
  ["'에미레이트'", "'Emirates'"],
  ["'카타르'", "'Qatar'"],
  ["'싱가포르'", "'Singapore'"],
  ["'대한항공'", "'Korean Air'"],
  ["'아시아나'", "'Asiana'"],
  ["'기타'", "'Other'"],
  ["'서울'", "'Seoul'"],
  ["'경기'", "'Gyeonggi'"],
  ["'부산'", "'Busan'"],
  ["'온라인'", "'Online'"],
  ["'2명'", "'2 people'"],
  ["'3명'", "'3 people'"],
  ["'4명'", "'4 people'"],
  ["'5명+'", "'5+'"],
  ["'평일 오전'", "'Weekday AM'"],
  ["'평일 오후'", "'Weekday PM'"],
  ["'주말'", "'Weekend'"],
  ["'매일'", "'Daily'"],
  ['스터디 모집하기', 'Create Study Group'],
  ['항공사', 'Airline'],
  ['지역', 'Region'],
  ['인원', 'Members'],
  ['시간대', 'Schedule'],
  ['제목을 입력하세요', 'Enter title'],
  ['내용을 작성해주세요', 'Write your content'],
  ['등록하기', 'Submit'],
  ['취소', 'Cancel'],
  ['제목과 내용을 입력해주세요.', 'Please enter title and content.'],
  ["'익명'", "'Anonymous'"],
  ['인증됨', 'Verified'],
  ['위치 확인 중...', 'Checking location...'],
  ['내 주변 먼저', 'Nearby First'],
  ['내 주변 스터디 보기', 'Show Nearby Study Groups'],
  ['위치 정보 사용에 동의해주세요.', 'Please allow location access.'],
  ['주변 스터디원을 검색합니다...', 'Searching nearby study partners...'],
  ['주변 3km 이내 스터디원', 'Partners within 3km'],
  ['합격 인증 후 작성 가능합니다', 'Available after verification'],
  ['면접 단계', 'Interview Stage'],
  ['>서류<', '>Application<'],
  ['>비디오면접<', '>Video Interview<'],
  ['>1차면접<', '>1st Interview<'],
  ['>파이널<', '>Final<'],
  ['후기 등록', 'Submit Review'],
  ['개', ' items'],
]);

// ===== token-rewards-en.html =====
tr('token-rewards-en.html', [
  ['토큰을 모아', 'Collect Tokens,'],
  ['<em>더 많이 연습하세요</em>', '<em>Practice More</em>'],
  ['출석, Invite Friends, Success Stories로 무료 토큰을 받을 수 있어요.', 'Earn free tokens through attendance, invites, and success stories.'],
  ['내 토큰', 'My Tokens'],
  ['만료까지', 'Until Expiry'],
  ['출석 <em>체크</em>', 'Daily <em>Attendance</em>'],
  ['매일 출석하면 토큰 1개!', '1 token per daily check-in!'],
  ['7일 연속 출석 시 보너스 3개 추가', '3 bonus tokens for 7-day streak'],
  ['오늘 출석하기', 'Check In Today'],
  ['이미 출석했습니다.', 'Already checked in.'],
  ["'일','월','화','수','목','금','토'", "'Sun','Mon','Tue','Wed','Thu','Fri','Sat'"],
  ['친구 <em>초대</em>', 'Invite <em>Friends</em>'],
  ['친구가 가입하면 나에게 토큰 3개, 친구에게 토큰 2개!', '3 tokens for you, 2 for your friend on signup!'],
  ['초대 현황', 'Invite Status'],
  ['초대한 친구', 'Friends Invited'],
  ['획득 토큰', 'Tokens Earned'],
  ['카카오톡 공유', 'Share KakaoTalk'],
  ['WhatsApp 공유', 'Share WhatsApp'],
  ['합격 <em>후기</em>', 'Success <em>Stories</em>'],
  ['합격 후기를 남기면 토큰 5개!', '5 tokens for posting a success story!'],
  ['합격 후기 작성하기', 'Write Success Story'],
  ['요금제 <em>선택</em>', 'Choose a <em>Plan</em>'],
  ['5 토큰', '5 Tokens'],
  ['50 토큰/월', '50 Tokens/mo'],
  ['무제한', 'Unlimited'],
  ['2년 올인원', '2-Year All-in-One'],
  ['19.9만원/월', '₩199,000/mo'],
  ['29.9만원/월', '₩299,000/mo'],
  ['250만원', '₩2,500,000'],
  ['라이브 수업 포함', 'Live classes included'],
  ['1:1 코치 피드백 포함', '1:1 coach feedback included'],
  ['모든 강의 영상 포함', 'All lecture videos included'],
  ['현재 플랜', 'Current Plan'],
  ['토큰이 부족합니다', 'Insufficient tokens'],
  ['토큰 충전 이벤트', 'Token Recharge Event'],
  ['첫 구독 시 토큰 2배 지급!', 'Double tokens on first subscription!'],
  ['상세보기', 'View Details'],
]);

// ===== daily-english-en.html =====
tr('daily-english-en.html', [
  ['오늘도 한 걸음,', 'One step at a time —'],
  ['<em>꾸준함이 합격의 비밀</em>', '<em>Consistency is the Secret</em>'],
  ['연속 출석일', 'Day Streak'],
  ['총 출석일', 'Total Days'],
  ['영어 액센트', 'English Accent'],
  ['답변 수준', 'Answer Level'],
  ['쉬운 버전 (초급)', 'Easy (Beginner)'],
  ['고급 버전 (중상급)', 'Advanced (Upper-Intermediate)'],
  ['질문 듣기', 'Listen to Question'],
  ['답변 녹음 시작', 'Start Recording'],
  ['답변 제출', 'Submit Answer'],
  ['더 연습하기', 'More Practice'],
  ['기내방송 쉐도잉', 'In-flight Announcement Shadowing'],
  ['따라하기', 'Repeat After'],
  ['듣기', 'Listen'],
  ['따라읽기 시작', 'Start Read-Along'],
  ['따라읽기 중지', 'Stop Read-Along'],
  ['다시 듣기', 'Listen Again'],
  ['다음 방송문', 'Next Announcement'],
  ['음성 입력 Standby 중...', 'Voice input standby...'],
  ['피드백을 생성하지 못했습니다.', 'Failed to generate feedback.'],
  ['질문을 먼저 받아주세요.', 'Please get a question first.'],
  ['녹음을 먼저 해주세요.', 'Please record first.'],
  ['피드백 중...', 'Generating feedback...'],
  ['질문을 듣고 영어로 답변하세요', 'Listen and answer in English'],
  ['AI가 피드백을 생성 중...', 'AI generating feedback...'],
  ["'일','월','화','수','목','금','토'", "'Sun','Mon','Tue','Wed','Thu','Fri','Sat'"],
  ['Southeast Asian English', ''],
  ['<option value="en-SG"></option>', ''],
]);

// ===== about-en.html =====
tr('about-en.html', [
  ['항공사 일등석의 Service Philosophy을', "First-class airline Service Philosophy"],
  ['당신의 커리어에 이식합니다', 'transplanted into your career'],
  ['AI로 완성하는 프리미엄 승무원 교육', 'Premium Cabin Crew Training Powered by AI'],
  ['원더풀크루 대표', 'WonderfulCrew Founder'],
  ['에미레이트항공 일등석 승무원 7년 경력으로', 'With 7 years as Emirates first-class crew,'],
  ['1,000명 이상의 합격생을 배출한 코칭 전문가', 'a coaching expert with 1,000+ successful placements'],
  ['20년간 쌓아온 현장 경험과 데이터를 AI에 담았습니다.', '20 years of field experience and data embedded in AI.'],
  ['13년 이상의 면접 코칭 경력', '13+ years of interview coaching'],
  ['에미레이트 항공 일등석', 'Emirates Airlines first-class'],
  ['사진<br>(추후 업데이트)', 'Photo<br>(Coming Soon)'],
  ['서비스 <em>철학</em>', 'Service <em>Philosophy</em>'],
  ['10가지 핵심 원칙', '10 Core Principles'],
  ['뻔한 답변 유도 금지', 'No Generic Answers'],
  ['지원자의 진짜 이야기를 끌어내야 합니다.', "Draw out the applicant's real story."],
  ['실제 경험을 기반으로 답하기', 'Answer from Real Experience'],
  ['검색해서 나오는 답이 아닌 직접 겪은 이야기만.', 'Only personal stories, not search-engine answers.'],
  ['고객의 기대를 넘어서는 서비스', 'Exceed Customer Expectations'],
  ['요청받은 것 이상을 제공하는 것이 진짜 서비스입니다.', 'True service means going beyond what was asked.'],
  ['진정성 있는 공감 표현', 'Authentic Empathy'],
  ['고객의 감정을 진심으로 이해하고 표현하세요.', "Truly understand and express the customer's feelings."],
  ['선제적 서비스 (Anticipation)', 'Proactive Service (Anticipation)'],
  ['고객이 요청하기 전에 필요를 파악하세요.', 'Identify needs before the customer asks.'],
  ["팀워크는 \"We\"로 말하기", 'Teamwork Means Saying "We"'],
  ['"I"가 아닌 "We"로. 팀의 성공이 진짜 성공입니다.', '"We" not "I." Team success is real success.'],
  ['컴플레인은 기회다 (Service Recovery)', 'Complaints Are Opportunities (Service Recovery)'],
  ['불만을 해결하면 오히려 더 큰 신뢰를 얻을 수 있습니다.', 'Resolving complaints can build even greater trust.'],
  ['디테일이 차이를 만든다', 'Details Make the Difference'],
  ['작은 배려가 잊지 못할 경험이 됩니다.', 'Small gestures create unforgettable experiences.'],
  ['면접은 긴장이 아니라 즐김', 'Enjoy the Interview'],
  ['면접을 즐기는 사람이 합격합니다.', 'Those who enjoy interviews succeed.'],
  ['자기 말로 표현하기', 'Express in Your Own Words'],
  ['외운 문장이 아닌 자기 언어로 말해야 진심이 전달됩니다.', 'Speak in your own words, not memorized sentences, to convey sincerity.'],
  ['현직 승무원 자문단', 'Active Crew Advisory Board'],
  ['10개 항공사 현직 승무원이 커리큘럼 감수와 면접 트렌드를 제공합니다.', '10 airline active crew members provide curriculum review and interview trends.'],
  ['에미레이트 현직', 'Emirates (Active)'],
  ['카타르 현직', 'Qatar (Active)'],
  ['싱가포르항공 현직', 'Singapore Airlines (Active)'],
  ['캐세이퍼시픽 현직', 'Cathay Pacific (Active)'],
  ['대한항공 현직', 'Korean Air (Active)'],
  ['아시아나 현직', 'Asiana (Active)'],
  ['서비스 교육 & 롤플레이 자문', 'Service Training & Roleplay Advisory'],
  ['면접 질문 트렌드 제공', 'Interview Question Trends'],
  ['커리큘럼 감수', 'Curriculum Review'],
  ['추후 업데이트 예정', 'Coming Soon'],
  ['자문위원', 'Advisor'],
]);

// ===== leveltest-en.html =====
tr('leveltest-en.html', [
  ['어떤 언어로', 'Which Language for'],
  ['<em>테스트</em>할까요?', 'Your <em>Test</em>?'],
  ['국내 항공사 준비 중이라면 한국어를,', 'Choose Korean for domestic airlines,'],
  ['외항사(에미레이트·카타르 등) 준비라면 영어를 선택하세요.', 'English for international airlines (Emirates, Qatar, etc.).'],
  ['두 언어 모두 테스트하면 종합 진단을 받을 수 있어요.', 'Test in both languages for a comprehensive assessment.'],
  ['한국어로 테스트', 'Test in Korean'],
  ['국내 항공사 면접 기준', 'Domestic airline interview standard'],
  ['영어로 테스트', 'Test in English'],
  ['외항사 면접 기준', 'International airline standard'],
  ['기본 정보', 'Basic Info'],
  ['간단한 정보를 입력해주세요.', 'Please enter your basic info.'],
  ['결과 분석에 활용됩니다.', 'Used for result analysis.'],
  ['이름</label>', 'Name</label>'],
  ['전화번호 (선택)</label>', 'Phone (optional)</label>'],
  ['이메일 (선택)</label>', 'Email (optional)</label>'],
  ['면접 교육 경험</label>', 'Interview Training Experience</label>'],
  ['없음', 'None'],
  ['독학', 'Self-study'],
  ['학원 수강', 'Academy'],
  ['1:1 코칭', '1:1 Coaching'],
  ['항공사 지원 경험</label>', 'Airline Application Experience</label>'],
  ['아직 지원한 적 없어요', 'Never applied yet'],
  ['지원했지만 서류 탈락', 'Applied but rejected at document stage'],
  ['면접까지 갔어요', 'Got to interview stage'],
  ['파이널까지 갔어요', 'Got to final stage'],
  ['현재 영어 수준</label>', 'Current English Level</label>'],
  ['기초 (인사/자기소개 정도)', 'Basic (greetings/self-intro)'],
  ['일상회화 가능', 'Conversational'],
  ['비즈니스 영어 가능', 'Business English'],
  ['원어민급', 'Near-native'],
  ['레벨 테스트 하기', 'Start Level Test'],
  ['영상 면접 테스트', 'Video Interview Test'],
  ['카메라를 켜고 질문에 답변해주세요.', 'Turn on your camera and answer the question.'],
  ['AI가 표정, 자세, 답변을 종합 분석합니다.', 'AI analyzes your expression, posture, and answer.'],
  ['카메라 시작', 'Start Camera'],
  ['녹화 시작', 'Start Recording'],
  ['녹화 중지', 'Stop Recording'],
  ['다시 찍기', 'Retake'],
  ['AI 분석 시작하기', 'Start AI Analysis'],
  ['카메라를 먼저 시작해주세요.', 'Please start camera first.'],
  ['녹화를 먼저 해주세요.', 'Please record first.'],
  ['AI가 분석 중이에요...', 'AI is analyzing...'],
  ['결과 & 추천', 'Results & Recommendations'],
  ['종합 점수', 'Overall Score'],
  ['강점', 'Strengths'],
  ['개선 포인트', 'Areas to Improve'],
  ['세부 점수', 'Detailed Scores'],
  ['추천 항공사', 'Recommended Airlines'],
  ['커리큘럼 시작하기', 'Start Curriculum'],
  ['다시 테스트하기', 'Retake Test'],
  ["'지원자'", "'Applicant'"],
  ["'미입력'", "'N/A'"],
  ['밝은 미소와 자연스러운 표정이 인상적입니다.', 'Impressive bright smile and natural expression.'],
  ['답변 구조가 논리적이며 핵심을 잘 전달합니다.', 'Logical answer structure that conveys key points well.'],
  ['영어 발음이 명확하고 자신감이 느껴집니다.', 'Clear English pronunciation with confidence.'],
  ['답변에 구체적인 경험 사례를 더 추가하면 좋겠습니다.', 'Add more specific experience examples to your answers.'],
  ['카메라를 정면으로 바라보는 연습이 필요합니다.', 'Practice looking directly at the camera.'],
  ['서비스 마인드를 보여주는 표현을 강화하세요.', 'Strengthen expressions that show service mindset.'],
  ['점', 'pts'],
  ['유창성', 'Fluency'],
  ['자신감', 'Confidence'],
  ['표정/자세', 'Expression/Posture'],
  ['내용 구성', 'Content Structure'],
  ['서비스 마인드', 'Service Mindset'],
  ['글로벌 서비스 기준에 맞는 준비도가 높습니다.', 'High readiness for global service standards.'],
  ['한국형 서비스와 잘 맞는 강점이 있습니다.', 'Strong fit for Korean-style service.'],
  ['안정적인 서비스 마인드가 돋보입니다.', 'Outstanding stable service mindset.'],
]);

console.log('=== Pass 6 complete ===');
