const fs=require('fs');
function tr(file, pairs) {
  if (!fs.existsSync(file)) { console.log('SKIP:', file); return; }
  let html = fs.readFileSync(file, 'utf8');
  let c = 0;
  pairs.forEach(([k, v]) => {
    if (html.includes(k)) { html = html.split(k).join(v); c++; }
  });
  if (c > 0) { fs.writeFileSync(file, html, 'utf8'); console.log(file + ': ' + c); }
}

// ===== about-en.html =====
tr('about-en.html', [
  ['원더풀크루를', 'WonderfulCrew'],
  ['<em>소개합니다</em>', '<em>Introduction</em>'],
  ['에미레이트 일등석 출신 대표와 현직 승무원 Advisory Board이 함께 만드는', 'Created by a former Emirates first-class crew founder and active crew Advisory Board —'],
  ['프리미엄 승무원 교육 플랫폼', 'A premium cabin crew education platform'],
  ['사진<br>(추후 업데이트)', 'Photo<br>(Coming Soon)'],
  ['대표 인사말', 'Founder Message'],
  ['에미레이트 항공 일등석 승무원 7년', '7 years as Emirates first-class cabin crew'],
  ['면접 코칭 경력 13년', '13 years of interview coaching'],
  ['22개국 965명+ 합격생 배출', '965+ successful placements from 22 countries'],
  ['서비스는 매뉴얼이 아니라 진심입니다.', 'Service is not a manual — it is sincerity.'],
  ['서비스 <em>철학</em>', 'Service <em>Philosophy</em>'],
  ['10가지 핵심 원칙', '10 Core Principles'],
  ['뻔한 답변 유도 금지', 'No generic answers allowed'],
  ['실제 경험을 기반으로 답하기', 'Answer based on real experience'],
  ['고객의 기대를 넘어서는 서비스', 'Service that exceeds expectations'],
  ['진정성 있는 공감 표현', 'Authentic empathy'],
  ['선제적 서비스 (Anticipation)', 'Proactive service (Anticipation)'],
  ['팀워크는 "We"로 말하기', 'Teamwork means saying "We"'],
  ['컴플레인은 기회다 (Service Recovery)', 'Complaints are opportunities (Service Recovery)'],
  ['디테일이 차이를 만든다', 'Details make the difference'],
  ['면접은 긴장이 아니라 즐김', 'Interviews are for enjoying, not stressing'],
  ['자기 말로 표현하기', 'Express in your own words'],
  ['Advisory <em>Board</em>', 'Advisory <em>Board</em>'],
  ['현직 승무원 자문단', 'Active Crew Advisory Board'],
  ['에미레이트 현직', 'Emirates (Active)'],
  ['카타르 현직', 'Qatar (Active)'],
  ['싱가포르항공 현직', 'Singapore Airlines (Active)'],
  ['캐세이퍼시픽 현직', 'Cathay Pacific (Active)'],
  ['대한항공 현직', 'Korean Air (Active)'],
  ['아시아나 현직', 'Asiana (Active)'],
  ['서비스 교육 & 롤플레이 자문', 'Service training & roleplay advisory'],
  ['면접 질문 트렌드 제공', 'Interview question trends'],
  ['커리큘럼 감수', 'Curriculum review'],
  ['년', 'yr'],
  ['명+', '+'],
  ['개국', 'countries'],
  ['코칭 경력', 'Coaching'],
  ['합격생', 'Graduates'],
  ['데이터 기반', 'Data-driven'],
]);

// ===== jobs-en.html =====
tr('jobs-en.html', [
  ['지금 열려있는', 'Currently Open'],
  ['<em>글로벌 항공사 채용</em>', '<em>Global Airline Careers</em>'],
  ['에미레이트, 카타르, 싱가포르, 캐세이, 대한항공, 아시아나   주요 항공사 채용 소식을 한 곳에서 확인하세요.', 'Emirates, Qatar, Singapore, Cathay, Korean Air, Asiana — all major airline recruitment news in one place.'],
  ['항공사별 <em>채용 현황</em>', 'Airline <em>Recruitment Status</em>'],
  ['채용중', 'Hiring'],
  ['서류 마감', 'Application Deadline'],
  ['오픈데이', 'Open Day'],
  ['상시 채용', 'Rolling Recruitment'],
  ['객실 승무원', 'Cabin Crew'],
  ['신입 승무원', 'New Cabin Crew'],
  ['채용 일정 보기', 'View Schedule'],
  ['지원 준비하기 →', 'Prepare Application →'],
  ['최신 <em>채용 뉴스</em>', 'Latest <em>Recruitment News</em>'],
  ['항공사 채용 뉴스를 실시간으로 업데이트합니다.', 'Real-time airline recruitment news updates.'],
  ['에미레이트항공 서울 오픈데이 개최', 'Emirates Seoul Open Day Announced'],
  ['카타르항공 한국인 승무원 상시채용', 'Qatar Airways Korean Crew Rolling Recruitment'],
  ['대한항공 신입 객실승무원 공개채용 예정', 'Korean Air New Cabin Crew Open Recruitment'],
  ['싱가포르항공 채용설명회 안내', 'Singapore Airlines Recruitment Info Session'],
  ['캐세이퍼시픽 2026 Cabin Crew 모집', 'Cathay Pacific 2026 Cabin Crew Recruitment'],
  ['전체 뉴스 보기 →', 'View All News →'],
]);

// ===== community-en.html =====
tr('community-en.html', [
  ['함께 준비하면', 'Prepare Together,'],
  ['<em>합격이 가까워져요</em>', '<em>Get Closer to Success</em>'],
  ['스터디를 구하고, 고민을 나누고, Interview Reviews와 Success Stories를 공유하세요.', 'Find study partners, share concerns, and post interview reviews and success stories.'],
  ['스터디 구해요', 'Find Study Partners'],
  ['내 주변 / 같은 항공사 스터디 찾기', 'Find nearby study groups for the same airline'],
  ['0개', '0'],
  ['자유롭게 이야기해요', 'Free Discussion Board'],
  ['면접 고민, 항공사 정보, 자유 토론', 'Interview worries, airline info, open discussion'],
  ['어땠나요?', 'How Was It?'],
  ['실제 면접 경험 공유', 'Share real interview experiences'],
  ['합격했어요!', 'I Got Accepted!'],
  ['합격 후기와 꿀팁 공유', 'Share success stories and tips'],
  ['에미레이트 스터디원 구합니다', 'Looking for Emirates study partners'],
  ['서울 강남 / 주 2회 / 영어 인터뷰', 'Seoul Gangnam / twice a week / English interview'],
  ['카타르 파이널 준비 스터디', 'Qatar Final Prep Study Group'],
  ['온라인 / 주 3회 / 파이널 집중', 'Online / 3x week / Final focus'],
  ['대한항공 면접 스터디', 'Korean Air Interview Study'],
  ['서울 / 주 2회 / 한국어 면접', 'Seoul / twice a week / Korean interview'],
  ['3번 탈락 후 원더풀크루와 함께 4번째 도전에서 합격했습니다. 롤플레이 연습이 정말 큰 도움이 됐어요. 포기하지 마세요!', 'After 3 rejections, I passed on my 4th attempt with WonderfulCrew. Roleplay practice was incredibly helpful. Never give up!'],
  ['영어가 부족했지만 쉬운 단어로 자신감 있게 말하는 연습을 반복했더니 파이널까지 통과했습니다. 감사합니다 코치님!', 'My English was lacking, but I practiced speaking confidently with simple words and passed through to the final. Thank you, coach!'],
  ['그루밍 가이드 보고 메이크업 확 바꿨더니 1차에서 바로 통과! 이미지가 정말 중요하다는 걸 체감했어요.', 'I changed my makeup after reading the grooming guide and passed the 1st round immediately! Image really matters.'],
  ['인증됨', 'Verified'],
  ['스터디 개설하기', 'Create Study Group'],
  ['근처 스터디원 찾기', 'Find Nearby Partners'],
  ['현재 위치 주변의 스터디원을 찾아보세요.', 'Find study partners near your current location.'],
  ['내 위치 기반 매칭 시작', 'Start Location-based Matching'],
  ['위치 정보 사용에 동의해주세요.', 'Please allow location access.'],
  ['주변 스터디원을 검색합니다...', 'Searching for nearby study partners...'],
  ['주변 3km 이내 스터디원', 'Study partners within 3km'],
]);

// ===== token-rewards-en.html =====
tr('token-rewards-en.html', [
  ['토큰을 모아', 'Collect Tokens,'],
  ['<em>더 많이 연습하세요</em>', '<em>Practice More</em>'],
  ['출석, Invite Friends, Success Stories로 무료 토큰을 받을 수 있어요.', 'Earn free tokens through attendance, inviting friends, and sharing success stories.'],
  ['내 토큰', 'My Tokens'],
  ['만료까지', 'Until Expiry'],
  ['출석 <em>체크</em>', 'Daily <em>Attendance</em>'],
  ['매일 출석하면 토큰 1개!', '1 token for daily attendance!'],
  ['7일 연속 출석 시 보너스 3개 추가', '3 bonus tokens for 7-day streak'],
  ['오늘 출석하기', 'Check In Today'],
  ['이미 출석했습니다.', 'Already checked in today.'],
  ['일', 'Sun'],
  ['월', 'Mon'],
  ['화', 'Tue'],
  ['수', 'Wed'],
  ['목', 'Thu'],
  ['금', 'Fri'],
  ['토', 'Sat'],
  ['친구 <em>초대</em>', 'Invite <em>Friends</em>'],
  ['친구가 가입하면 나에게 토큰 3개, 친구에게 토큰 2개!', '3 tokens for you, 2 for your friend when they sign up!'],
  ['초대 현황', 'Invite Status'],
  ['초대한 친구', 'Friends Invited'],
  ['획득 토큰', 'Tokens Earned'],
  ['카카오톡 공유', 'Share via KakaoTalk'],
  ['WhatsApp 공유', 'Share via WhatsApp'],
  ['합격 <em>후기</em>', 'Success <em>Stories</em>'],
  ['합격 후기를 남기면 토큰 5개!', '5 tokens for posting a success story!'],
  ['합격 후기 작성하기', 'Write a Success Story'],
  ['요금제 <em>선택</em>', 'Choose a <em>Plan</em>'],
  ['5 토큰', '5 Tokens'],
  ['50 토큰/월', '50 Tokens/mo'],
  ['무제한', 'Unlimited'],
  ['2년 올인원', '2-Year All-in-One'],
  ['19.9만원/월', '₩199,000/mo'],
  ['29.9만원/월', '₩299,000/mo'],
  ['250만원', '₩2,500,000'],
  ['라이브 수업 포함', 'Live classes included'],
  ['1:1 코치 피드백 포함', '1:1 coach feedback included'],
  ['모든 강의 영상 포함', 'All lecture videos included'],
  ['현재 플랜', 'Current Plan'],
]);

// ===== daily-english-en.html =====
tr('daily-english-en.html', [
  ['오늘도 한 걸음,', 'One step at a time —'],
  ['<em>꾸준함이 합격의 비밀</em>', '<em>Consistency is the Secret</em>'],
  ['연속', 'Streak'],
  ['총 연습', 'Total Practice'],
  ['레벨 선택', 'Select Level'],
  ['>쉬운</option>', '>Easy</option>'],
  ['>고급</option>', '>Advanced</option>'],
  ['악센트 선택', 'Select Accent'],
  ['질문 받기', 'Get Question'],
  ['답변 녹음', 'Record Answer'],
  ['녹음 중지', 'Stop Recording'],
  ['AI 피드백 받기', 'Get AI Feedback'],
  ['다음 질문', 'Next Question'],
  ['피드백 확인 중...', 'Checking feedback...'],
  ['녹음을 먼저 해주세요.', 'Please record first.'],
  ['쉐도잉 <em>연습</em>', 'Shadowing <em>Practice</em>'],
  ['원어민 발음을 듣고 따라하세요', 'Listen and repeat after the native speaker'],
  ['재생', 'Play'],
  ['녹음 시작', 'Start Recording'],
  ['다시 듣기', 'Listen Again'],
  ['음성 입력 Standby 중...', 'Voice input standby...'],
  ['개선된 답변', 'Improved Answer'],
  ['AI 피드백', 'AI Feedback'],
]);

console.log('=== Pass 4 complete ===');
