// 파트너/도입 문의 폼 저장 (partner.html). 공개 폼이라 인증 없음 — service_role 로 insert.
// Supabase 테이블 `inquiries` 필요 (아래 SQL 참고):
//   create table inquiries (
//     id bigint generated by default as identity primary key,
//     org text, name text, email text, phone text,
//     sector text, scale text, message text, source text,
//     created_at timestamptz default now()
//   );
const { createClient } = require('@supabase/supabase-js');

function clip(v, n) { return (typeof v === 'string' ? v : '').trim().slice(0, n); }

module.exports = async function (req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ ok: false, error: 'POST only' });

  const url = process.env.SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_KEY;
  if (!url || !serviceKey) return res.status(500).json({ ok: false, error: 'server_config_missing' });

  let body = req.body;
  if (typeof body === 'string') { try { body = JSON.parse(body); } catch { body = {}; } }
  body = body || {};

  const row = {
    org: clip(body.org, 120),
    name: clip(body.name, 80),
    email: clip(body.email, 120),
    phone: clip(body.phone, 40),
    sector: clip(body.sector, 80),
    scale: clip(body.scale, 80),
    message: clip(body.message, 2000),
    source: clip(body.source, 60) || 'partner-landing'
  };

  // 최소 검증: 기관명 + 담당자 + 이메일
  if (!row.org || !row.name || !row.email) {
    return res.status(400).json({ ok: false, error: 'org, name, email required' });
  }

  try {
    const db = createClient(url, serviceKey);
    const { error } = await db.from('inquiries').insert(row);
    if (error) {
      console.warn('[partner-inquiry] insert error:', error.message);
      return res.status(500).json({ ok: false, error: 'insert_failed' });
    }
    res.status(200).json({ ok: true });
  } catch (e) {
    res.status(500).json({ ok: false, error: e.message });
  }
};
