// 설명회 신청 폼 저장 (seminar.html). 공개 폼이라 인증 없음 — service_role 로 insert.
// Supabase 테이블 `seminar_signups` 필요 (아래 SQL 참고):
//   create table seminar_signups (
//     id bigint generated by default as identity primary key,
//     name text, phone text, email text, airline text,
//     created_at timestamptz default now()
//   );
const { createClient } = require('@supabase/supabase-js');

function clip(v, n) { return (typeof v === 'string' ? v : '').trim().slice(0, n); }

module.exports = async function (req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ ok: false, error: 'POST only' });

  const url = process.env.SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_KEY;
  if (!url || !serviceKey) return res.status(500).json({ ok: false, error: 'server_config_missing' });

  let body = req.body;
  if (typeof body === 'string') { try { body = JSON.parse(body); } catch { body = {}; } }
  body = body || {};

  const name = clip(body.name, 80);
  const phone = clip(body.phone, 40);
  const email = clip(body.email, 120);
  const airline = clip(body.airline, 80);

  // 최소 검증: 이름 + (연락처 또는 이메일)
  if (!name || (!phone && !email)) {
    return res.status(400).json({ ok: false, error: 'name and phone/email required' });
  }

  try {
    const db = createClient(url, serviceKey);
    const { error } = await db.from('seminar_signups').insert({ name, phone, email, airline });
    if (error) {
      console.warn('[seminar-signup] insert error:', error.message);
      return res.status(500).json({ ok: false, error: 'insert_failed' });
    }
    res.status(200).json({ ok: true });
  } catch (e) {
    res.status(500).json({ ok: false, error: e.message });
  }
};
